import { Component, inject, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { TranslateService } from "@ngx-translate/core";
import {
    DigitalServiceFootprint,
    GraphDescriptionContent,
} from "src/app/core/interfaces/digital-service.interfaces";
import { convertToGlobalVision } from "src/app/core/service/mapper/digital-service";

@Component({
    selector: "app-digital-services-compare-versions",
    templateUrl: "./digital-services-compare-versions.component.html",
    styleUrl: "./digital-services-compare-versions.component.scss",
})
export class DigitalServicesCompareVersionsComponent implements OnInit {
    private readonly route = inject(ActivatedRoute);
    version1Id: string = "";
    version2Id: string = "";
    globalVisionChartData: DigitalServiceFootprint[] | undefined;
    outPhysicalEquipments = [
        {
            name: "Server D",
            criterion: "RESOURCE_USE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg Sb eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 1.0832975999999999e-8,
            peopleEqImpact: 3.957251506849315e-7,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server B",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg CO2 eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 153.82150875,
            peopleEqImpact: 0.18070074449339207,
            electricityConsumption: 1261.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server A",
            criterion: "RESOURCE_USE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg Sb eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 6.9906547728e-7,
            peopleEqImpact: 2.5536638439452056e-5,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Network 1",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Network",
            unit: "kg CO2 eq",
            reference: "fixed-line-network-1",
            countValue: 1,
            unitImpact: 0.02229274196100131,
            peopleEqImpact: 2.618824312599273e-5,
            electricityConsumption: 180.924217704336,
            quantity: 0.0015151515151515152,
            numberOfUsers: 0.0,
            lifespan: 0.0015193026151930262,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Terminal 1",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Terminal",
            unit: "kg CO2 eq",
            reference: "laptop-3",
            countValue: 1,
            unitImpact: 1.3515981735159817e-4,
            peopleEqImpact: 1.5877805268910212e-7,
            electricityConsumption: 0.0,
            quantity: 4.5662100456621003e-4,
            numberOfUsers: 2.0,
            lifespan: 0.00228310502283105,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Terminal 1",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Terminal",
            unit: "kg CO2 eq",
            reference: "laptop-3",
            countValue: 1,
            unitImpact: 0.0010805866438356165,
            peopleEqImpact: 1.2694116227143805e-6,
            electricityConsumption: 29.1,
            quantity: 4.5662100456621003e-4,
            numberOfUsers: 2.0,
            lifespan: 0.00228310502283105,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Network 1",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Network",
            unit: "kg CO2 eq",
            reference: "fixed-line-network-1",
            countValue: 1,
            unitImpact: 8.174573604901473e-4,
            peopleEqImpact: 9.603023324407016e-7,
            electricityConsumption: 0.0,
            quantity: 0.0015151515151515152,
            numberOfUsers: 0.0,
            lifespan: 0.0015193026151930262,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server A",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg CO2 eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 2014.31766375,
            peopleEqImpact: 2.3663056255506607,
            electricityConsumption: 16513.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Terminal 1",
            criterion: "RESOURCE_USE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Terminal",
            unit: "kg Sb eq",
            reference: "laptop-3",
            countValue: 1,
            unitImpact: 6.45512410958904e-10,
            peopleEqImpact: 2.3580362044160876e-8,
            electricityConsumption: 29.1,
            quantity: 4.5662100456621003e-4,
            numberOfUsers: 2.0,
            lifespan: 0.00228310502283105,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Network 1",
            criterion: "RESOURCE_USE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Network",
            unit: "kg Sb eq",
            reference: "fixed-line-network-1",
            countValue: 1,
            unitImpact: 1.3317064107928941e-8,
            peopleEqImpact: 4.864680952668106e-7,
            electricityConsumption: 180.924217704336,
            quantity: 0.0015151515151515152,
            numberOfUsers: 0.0,
            lifespan: 0.0015193026151930262,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server B",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg CO2 eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 4.2288,
            peopleEqImpact: 0.004967753303964757,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server D",
            criterion: "RESOURCE_USE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg Sb eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 0.004292136,
            peopleEqImpact: 0.15679035616438358,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Network 1",
            criterion: "RESOURCE_USE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Network",
            unit: "kg Sb eq",
            reference: "fixed-line-network-1",
            countValue: 1,
            unitImpact: 2.279754098360656e-13,
            peopleEqImpact: 8.327868852459017e-12,
            electricityConsumption: 0.0,
            quantity: 0.0015151515151515152,
            numberOfUsers: 0.0,
            lifespan: 0.0015193026151930262,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server A",
            criterion: "RESOURCE_USE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg Sb eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 0.0012032973561,
            peopleEqImpact: 0.04395606780273973,
            electricityConsumption: 16513.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server C",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg CO2 eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 18.4141233447525,
            peopleEqImpact: 0.021631862960061674,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Terminal 1",
            criterion: "RESOURCE_USE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Terminal",
            unit: "kg Sb eq",
            reference: "laptop-3",
            countValue: 1,
            unitImpact: 1.095890410958904e-6,
            peopleEqImpact: 4.0032526427722525e-5,
            electricityConsumption: 0.0,
            quantity: 4.5662100456621003e-4,
            numberOfUsers: 2.0,
            lifespan: 0.00228310502283105,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server A",
            criterion: "RESOURCE_USE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg Sb eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 0.016298416,
            peopleEqImpact: 0.5953759269406392,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server C",
            criterion: "RESOURCE_USE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg Sb eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 6.9906547728e-7,
            peopleEqImpact: 2.5536638439452056e-5,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Terminal 1",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Terminal",
            unit: "kg CO2 eq",
            reference: "laptop-3",
            countValue: 1,
            unitImpact: 0.028127853881278538,
            peopleEqImpact: 3.3043000154218545e-5,
            electricityConsumption: 0.0,
            quantity: 4.5662100456621003e-4,
            numberOfUsers: 2.0,
            lifespan: 0.00228310502283105,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server D",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg CO2 eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 153.82150875,
            peopleEqImpact: 0.18070074449339207,
            electricityConsumption: 1261.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server A",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg CO2 eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 1495.26784,
            peopleEqImpact: 1.7565554654919235,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server B",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg CO2 eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 0.27574847999999996,
            peopleEqImpact: 3.23933603524229e-4,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server D",
            criterion: "RESOURCE_USE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg Sb eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 9.18886917e-5,
            peopleEqImpact: 0.0033566645369863014,
            electricityConsumption: 1261.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server B",
            criterion: "RESOURCE_USE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg Sb eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 1.0832975999999999e-8,
            peopleEqImpact: 3.957251506849315e-7,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server C",
            criterion: "RESOURCE_USE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg Sb eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 5.085164e-6,
            peopleEqImpact: 1.8575941552511415e-4,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server A",
            criterion: "RESOURCE_USE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg Sb eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 5.085164e-6,
            peopleEqImpact: 1.8575941552511415e-4,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server D",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg CO2 eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 2549.916,
            peopleEqImpact: 2.995496035242291,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server B",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg CO2 eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 2549.916,
            peopleEqImpact: 2.995496035242291,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Network 1",
            criterion: "RESOURCE_USE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Network",
            unit: "kg Sb eq",
            reference: "fixed-line-network-1",
            countValue: 1,
            unitImpact: 2.236297400231826e-6,
            peopleEqImpact: 8.169122923221283e-5,
            electricityConsumption: 0.0,
            quantity: 0.0015151515151515152,
            numberOfUsers: 0.0,
            lifespan: 0.0015193026151930262,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Network 1",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Network",
            unit: "kg CO2 eq",
            reference: "fixed-line-network-1",
            countValue: 1,
            unitImpact: 5.803010432190759e-6,
            peopleEqImpact: 6.817046029005297e-9,
            electricityConsumption: 0.0,
            quantity: 0.0015151515151515152,
            numberOfUsers: 0.0,
            lifespan: 0.0015193026151930262,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server B",
            criterion: "RESOURCE_USE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg Sb eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 1.4627840000000002e-5,
            peopleEqImpact: 5.343503196347033e-4,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server C",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg CO2 eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 3.4044280000000002,
            peopleEqImpact: 0.003999328046989721,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Terminal 1",
            criterion: "RESOURCE_USE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Terminal",
            unit: "kg Sb eq",
            reference: "laptop-3",
            countValue: 1,
            unitImpact: 3.4977168949771686e-10,
            peopleEqImpact: 1.2777048018181438e-8,
            electricityConsumption: 0.0,
            quantity: 4.5662100456621003e-4,
            numberOfUsers: 2.0,
            lifespan: 0.00228310502283105,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server A",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg CO2 eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 3.4044280000000002,
            peopleEqImpact: 0.003999328046989721,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Network 1",
            criterion: "RESOURCE_USE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Network",
            unit: "kg Sb eq",
            reference: "fixed-line-network-1",
            countValue: 1,
            unitImpact: 1.328179334326875e-9,
            peopleEqImpact: 4.851796655075343e-8,
            electricityConsumption: 0.0,
            quantity: 0.0015151515151515152,
            numberOfUsers: 0.0,
            lifespan: 0.0015193026151930262,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server D",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg CO2 eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 4.2288,
            peopleEqImpact: 0.004967753303964757,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Terminal 1",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Terminal",
            unit: "kg CO2 eq",
            reference: "laptop-3",
            countValue: 1,
            unitImpact: 0.0016815141018858449,
            peopleEqImpact: 1.975346962567806e-6,
            electricityConsumption: 0.0,
            quantity: 4.5662100456621003e-4,
            numberOfUsers: 2.0,
            lifespan: 0.00228310502283105,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server B",
            criterion: "RESOURCE_USE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg Sb eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 0.004292136,
            peopleEqImpact: 0.15679035616438358,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server D",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg CO2 eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 0.27574847999999996,
            peopleEqImpact: 3.23933603524229e-4,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server C",
            criterion: "RESOURCE_USE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg Sb eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 0.0012032973561,
            peopleEqImpact: 0.04395606780273973,
            electricityConsumption: 16513.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Terminal 1",
            criterion: "RESOURCE_USE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Terminal",
            unit: "kg Sb eq",
            reference: "laptop-3",
            countValue: 1,
            unitImpact: 6.590225324200913e-11,
            peopleEqImpact: 2.4073882462834384e-9,
            electricityConsumption: 0.0,
            quantity: 4.5662100456621003e-4,
            numberOfUsers: 2.0,
            lifespan: 0.00228310502283105,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server C",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg CO2 eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 2014.31766375,
            peopleEqImpact: 2.3663056255506607,
            electricityConsumption: 16513.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server A",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "TRANSPORTATION",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg CO2 eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 18.4141233447525,
            peopleEqImpact: 0.021631862960061674,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server D",
            criterion: "RESOURCE_USE",
            lifecycleStep: "END_OF_LIFE",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg Sb eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 1.4627840000000002e-5,
            peopleEqImpact: 5.343503196347033e-4,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server B",
            criterion: "RESOURCE_USE",
            lifecycleStep: "USING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Dedicated Server",
            unit: "kg Sb eq",
            reference: "storage-bay--3",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 9.18886917e-5,
            peopleEqImpact: 0.0033566645369863014,
            electricityConsumption: 1261.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Network 1",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Network",
            unit: "kg CO2 eq",
            reference: "fixed-line-network-1",
            countValue: 1,
            unitImpact: 0.017527736380195395,
            peopleEqImpact: 2.059058605602983e-5,
            electricityConsumption: 0.0,
            quantity: 0.0015151515151515152,
            numberOfUsers: 0.0,
            lifespan: 0.0015193026151930262,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server C",
            criterion: "CLIMATE_CHANGE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg CO2 eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 1495.26784,
            peopleEqImpact: 1.7565554654919235,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
        {
            name: "Server C",
            criterion: "RESOURCE_USE",
            lifecycleStep: "MANUFACTURING",
            statusIndicator: "OK",
            location: "France",
            equipmentType: "Shared Server",
            unit: "kg Sb eq",
            reference: "rack-server--30",
            hostingEfficiency: "Medium",
            countValue: 1,
            unitImpact: 0.016298416,
            peopleEqImpact: 0.5953759269406392,
            electricityConsumption: 0.0,
            quantity: 1.0,
            numberOfUsers: 0.0,
            lifespan: 5.0,
            commonFilters: [""],
            filters: [""],
        },
    ] as any;
    outVirtualEquipments = [];

    private readonly translate = inject(TranslateService);
    ngOnInit(): void {
        this.route.queryParams.subscribe((params) => {
            this.version1Id = params["version1"];
            this.version2Id = params["version2"];
            // Load and compare the versions using these IDs
        });

        this.globalVisionChartData = convertToGlobalVision(
            this.outPhysicalEquipments,
            this.outVirtualEquipments,
        );
    }

    getContentText(): GraphDescriptionContent {
        // const isBarChart = this.chartType() === "bar";
        // const isIncludeCriteria = Object.keys(this.globalStore.criteriaList()).includes(
        //     this.selectedCriteria,
        // );
        // let translationKey: string;
        // let textDescription: string = "";
        // if (isBarChart) {
        //     translationKey = this.getBarTranslateKey();
        //     textDescription = this.getBarChartTextDescription(translationKey);
        // } else {
        //     const criteriaKey = this.selectedCriteria
        //         .toLowerCase()
        //         .replaceAll(/\s+/g, "-");
        //     if (isIncludeCriteria) {
        //         //Criteria View
        //         translationKey = "ds-graph-description.criteria.";
        //         textDescription = this.getCriteriaTextDescription(
        //             translationKey,
        //             criteriaKey,
        //         );
        //     } else {
        //         // Global Vision
        //         translationKey = `ds-graph-description.${criteriaKey}.`;
        //         textDescription = this.getGlobalVisionTextDescription(translationKey);
        //     }
        // }
        // const key =
        //     "criteria." + this.selectedCriteria.toLowerCase().replaceAll(" ", "-") + ".";

        return {
            description: this.translate.instant(
                `digital-services.comparison.description`,
                {
                    version1Name: "A",
                    version2Name: "B",
                    impactsV1: "V1",
                    impactsV2: "V2",
                },
            ),
            scale: this.translate.instant(`digital-services.comparison.scale`),
            textDescription: this.translate.instant(
                `digital-services.comparison.text-description`,
            ),
            // description: this.translate.instant(`${translationKey}description`, {
            //     criteria: this.impacts.flatMap((impact) => impact.title).join(", "),
            // }),
            // scale: isIncludeCriteria
            //     ? this.translate.instant(`${key}scale`)
            //     : this.translate.instant(`${translationKey}scale`),
            // textDescription: textDescription,
        };
    }
}
