openapi: 3.0.3
info:
  title: Swagger GreenIT - Open API 3.0 - AI Infra Indicators
  description: This is a GreenIT Server based on the OpenAPI 3.0 specification.
  version: 1.0.0

tags:
  - name: ai-infra-inputs
    description: Endpoint for ai infra inputs - datacenter

paths:
  /organizations/{organization}/workspaces/{workspace}/digital-services/{digitalServiceUid}/ai-infra-input:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/digitalServiceUidPathParam'

    post:
      tags:
        - ai-infra-inputs
      summary: Post ai infra from one digital service
      x-custom-role: "hasRole('ROLE_ECO_MIND_AI_WRITE')"
      operationId: postDigitalServiceInputsAiInfraRest
      requestBody:
        description: ai-infra
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InAiInfrastructureRest"
      responses:
        '200':
          description: return ai-infra created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InPhysicalEquipmentRest"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

    get:
      tags:
        - ai-infra-inputs
      summary: Get ai infra for a digital service
      x-custom-role: "hasRole('ROLE_ECO_MIND_AI_READ')"
      operationId: getDigitalServiceInputsAiInfraRest
      responses:
        '200':
          description: AI infra fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InAiInfrastructureRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: AI infra not found
        '500':
          $ref: "#/components/responses/InternalServerError"

    put:
      tags:
        - ai-infra-inputs
      summary: Update ai infra for a digital service
      x-custom-role: "hasRole('ROLE_ECO_MIND_AI_WRITE')"
      operationId: updateDigitalServiceInputsAiInfraRest
      requestBody:
        description: ai-infra to update
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InAiInfrastructureRest"
      responses:
        '200':
          description: AI infra updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InPhysicalEquipmentRest"
        '400':
          description: Invalid input
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: AI infra not found
        '500':
          $ref: "#/components/responses/InternalServerError"
