openapi: 3.0.3
info:
  title: Swagger GreenIT - Open API 3.0 - AI Infra Indicators
  description: This is a GreenIT Server based on the OpenAPI 3.0 specification.
  version: 1.0.0

tags:
  - name: ai-infra-inputs
    description: Endpoint for ai infra inputs - datacenter

paths:
  /subscribers/{subscriber}/organizations/{organization}/digital-services/{digitalServiceUid}/ai-infra-input:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/digitalServiceUidPathParam'

    post:
      tags:
        - ai-infra-inputs
      summary: Post ai infra from one digital service
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: postDigitalServiceInputsInAiInfrastructureRest
      requestBody:
        description: ai-infra
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InAiInfrastructureRest"
      responses:
        '200':
          description: return ai-infra created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InPhysicalEquipmentRest"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
