openapi: "3.0.3"
info:
  title: Swagger GreenIT - Open API 3.0 - AI Service
  description: This is a GreenIT Server based on the OpenAPI 3.0 specification.
  version: "1.0.0"

tags:
  - name: ai-service
    description: All endpoint for ai service
paths:
  /ecomindai/estimation/type/{type}/stage/{stage}:
    post:
      tags:
        - ai-service
      summary: Get the energy consumption & runtime estimations of your ai configurations and the associated recommendations to reduce this impact
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: launchAIServiceEstimation
      parameters:
        - $ref: "#/components/parameters/typePathParam"
        - $ref: "#/components/parameters/stagePathParam"
      requestBody:
        description: Input array of ai configs that need to be estimated
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/AIConfigurationRest"
      responses:
        "200":
          description: Return the energy consumption & runtime estimations and recommendations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AIServiceEstimationRest"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /ecomindai/aiModelConfig/type/{type}:
    get:
      tags:
        - ai-service
      summary: Get the available configurations for LLMs in term of name, nb_parameters, framework & quantization
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getAIModelConfigurations
      parameters:
        - $ref: "#/components/parameters/typePathParam"
      responses:
        "200":
          description: Return a list of existing configurations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AIModelConfigRest"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"