openapi: "3.0.3"
info:
  title: Swagger GreenIT - Open API 3.0 - AI-PARAM
  description: This is a Inventory Server based on the OpenAPI 3.0 specification.
  version: '1.0.0'

tags:
  - name: ai-parameter
    description: Endpoint for ai-parameter

paths:
  /subscribers/{subscriber}/organizations/{organization}/digital-services/ai-parameter-input:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
    post:
      tags:
        - ai-parameter
      summary: Create API POST for ai parameters
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: createAiParameter

      requestBody:
        description: ai parameter details to create.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AiParameterRest"
      responses:
        '201':
          description: Return the ai parameter created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AiParameterRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"


