openapi: 3.0.3
info:
  title: Swagger GreenIT - Open API 3.0 - Digital Service Version Indicators
  description: This is a GreenIT Server based on the OpenAPI 3.0 specification.
  version: 1.0.0

tags:
  - name: digital-service-version-inputs-datacenter
    description: Endpoint for digital service version inputs - datacenter
  - name: digital-service-version-inputs-physical-equipment
    description: Endpoint for digital service version inputs - physical-equipment
  - name: digital-service-version-inputs-virtual-equipment
    description: Endpoint for digital service version inputs - virtual-equipment

paths:
  /organizations/{organization}/workspaces/{workspace}/digital-service-version/{digitalServiceVersionUid}/inputs/datacenters:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/digitalServiceVersionUidPathParam'
    get:
      tags:
        - digital-service-version-inputs-datacenter
      summary: Get datacenters from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceVersionInputsDatacentersRest
      responses:
        '200':
          description: return digital service version in datacenters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InDatacenterRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - digital-service-version-inputs-datacenter
      summary: Post datacenter from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: postDigitalServiceVersionInputsDatacentersRest
      requestBody:
        description: datacenter
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InDatacenterRest"
      responses:
        '200':
          description: return datacenter created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InDatacenterRest"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
  /organizations/{organization}/workspaces/{workspace}/digital-service-version/{digitalServiceVersionUid}/inputs/datacenters/{id}:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/digitalServiceVersionUidPathParam'
      - $ref: '#/components/parameters/idPathParam'
    get:
      tags:
        - digital-service-version-inputs-datacenter
      summary: Get datacenter from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceVersionInputsDatacenterRest
      responses:
        '200':
          description: return digital service version in datacenter with id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InDatacenterRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
    put:
      tags:
        - digital-service-version-inputs-datacenter
      summary: Update the datacenter from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: putDigitalServiceVersionInputsDatacenterRest
      requestBody:
        description: datacenter
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InDatacenterRest"
      responses:
        '200':
          description: return datacenter in digital service version in datacenter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InDatacenterRest"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

    delete:
      tags:
        - digital-service-version-inputs-datacenter
      summary: delete datacenter from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: deleteDigitalServiceVersionInputsDatacenterRest
      responses:
        '204':
          description: No content
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /organizations/{organization}/workspaces/{workspace}/digital-service-version/{digitalServiceVersionUid}/inputs/physical-equipments:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/digitalServiceVersionUidPathParam'
    get:
      tags:
        - digital-service-version-inputs-physical-equipment
      summary: Get physical equipments from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceVersionInputsPhysicalEquipmentsRest
      responses:
        '200':
          description: return digital service version in physical equipments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InPhysicalEquipmentRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - digital-service-version-inputs-physical-equipment
      summary: Post physical equipment from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: postDigitalServiceVersionInputsPhysicalEquipmentsRest
      requestBody:
        description: physical equipment
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InPhysicalEquipmentRest"
      responses:
        '200':
          description: return physical equipment created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InPhysicalEquipmentRest"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
  /organizations/{organization}/workspaces/{workspace}/digital-service-version/{digitalServiceVersionUid}/inputs/physical-equipments/{id}:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/digitalServiceVersionUidPathParam'
      - $ref: '#/components/parameters/idPathParam'
    get:
      tags:
        - digital-service-version-inputs-physical-equipment
      summary: Get physical equipment from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceVersionInputsPhysicalEquipmentRest
      responses:
        '200':
          description: return digital service version in physical equipment with id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InPhysicalEquipmentRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
    put:
      tags:
        - digital-service-version-inputs-physical-equipment
      summary: Update the physical equipment from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: putDigitalServiceVersionInputsPhysicalEquipmentRest
      requestBody:
        description: physical equipment
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InPhysicalEquipmentRest"
      responses:
        '200':
          description: return digital service version in virtual equipment with id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InPhysicalEquipmentRest"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

    delete:
      tags:
        - digital-service-version-inputs-physical-equipment
      summary: delete physical equipment from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: deleteDigitalServiceVersionInputsPhysicalEquipmentRest
      responses:
        '204':
          description: No content
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /organizations/{organization}/workspaces/{workspace}/digital-service-version/{digitalServiceVersionUid}/inputs/virtual-equipments:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/digitalServiceVersionUidPathParam'
    get:
      tags:
        - digital-service-version-inputs-virtual-equipment
      summary: Get virtual equipments from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceVersionInputsVirtualEquipmentsRest
      responses:
        '200':
          description: return digital service version in virtual equipments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InVirtualEquipmentRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
    put:
      tags:
        - digital-service-version-inputs-virtual-equipment
      summary: Update or delete virtual equipments from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      parameters:
        - $ref: "#/components/parameters/physicalEqpIdQueryParam"
      operationId: updateDigitalServiceVersionInputsVirtualEquipmentRest
      requestBody:
        description: virtual equipment
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/InVirtualEquipmentRest"
      responses:
        '200':
          description: return digital service version in virtual equipment with id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InVirtualEquipmentRest"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - digital-service-version-inputs-virtual-equipment
      summary: Post virtual equipment from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: postDigitalServiceVersionInputsVirtualEquipmentsRest
      requestBody:
        description: virtual equipment
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InVirtualEquipmentRest"
      responses:
        '200':
          description: return virtual equipment created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InVirtualEquipmentRest"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
  /organizations/{organization}/workspaces/{workspace}/digital-service-version/{digitalServiceVersionUid}/inputs/virtual-equipments/{id}:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/digitalServiceVersionUidPathParam'
      - $ref: '#/components/parameters/idPathParam'
    get:
      tags:
        - digital-service-version-inputs-virtual-equipment
      summary: Get virtual equipment from one digital service
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceVersionInputsVirtualEquipmentRest
      responses:
        '200':
          description: return digital service version in virtual equipment with id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InVirtualEquipmentRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
    put:
      tags:
        - digital-service-version-inputs-virtual-equipment
      summary: Update the virtual equipment from one digital service
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: putDigitalServiceVersionInputsVirtualEquipmentRest
      requestBody:
        description: virtual equipment
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InVirtualEquipmentRest"
      responses:
        '200':
          description: return digital service version in virtual equipment with id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InVirtualEquipmentRest"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

    delete:
      tags:
        - digital-service-version-inputs-virtual-equipment
      summary: delete virtual equipment from one digital service version
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      operationId: deleteDigitalServiceVersionInputsVirtualEquipmentRest
      responses:
        '204':
          description: No content
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
