openapi: 3.0.3
info:
  title: Swagger GreenIT - Open API 3.0 - Inventory Indicators
  description: This is a GreenIT Server based on the OpenAPI 3.0 specification.
  version: 1.0.0

tags:
  - name: inventory-outputs
    description: Endpoint for inventory outputs

paths:
  /organizations/{organization}/workspaces/{workspace}/inventories/{inventoryId}/outputs/physical-equipments:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/inventoryIdPathParam'
    get:
      tags:
        - inventory-outputs
      summary: Get physical equipments from one inventory
      x-custom-role: "hasRole('INVENTORY_READ')"
      operationId: getInventoryOutputsPhysicalEquipmentsRest
      responses:
        '200':
          description: return inventory output physical equipments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OutPhysicalEquipmentRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /organizations/{organization}/workspaces/{workspace}/inventories/{inventoryId}/outputs/virtual-equipments:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/inventoryIdPathParam'
    get:
      tags:
        - inventory-outputs
      summary: Get virtual equipments from one inventory
      x-custom-role: "hasRole('INVENTORY_READ')"
      operationId: getInventoryOutputsVirtualEquipmentsRest
      responses:
        '200':
          description: return inventory output virtual equipments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OutVirtualEquipmentRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /organizations/{organization}/workspaces/{workspace}/inventories/{inventoryId}/outputs/applications:
    parameters:
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/workspacePathParam'
      - $ref: '#/components/parameters/inventoryIdPathParam'
    get:
      tags:
        - inventory-outputs
      summary: Get applications from one inventory
      x-custom-role: "hasRole('INVENTORY_READ')"
      operationId: getInventoryOutputsApplicationsRest
      responses:
        '200':
          description: return inventory output applications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OutApplicationRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
